services:
  vite-app:
    image: node:18-alpine3.17
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install -g pnpm@latest && pnpm install --frozen-lockfile && pnpm run build"
  
  nginx:
    image: nginx:stable
    depends_on:
      - vite-app
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped